export const LABELS = {
    GROSS_MONTH_INCOME: 'Ваш місячний дохід',
    GROSS_DESCRIPTION_LABEL: 'Без вирахування податків',
    CURRENCY: 'Валюта',
    WITHOUT_TAXES: 'Без вирахування податків',
    NET_YEAR_INCOME: 'Чистий дохід на рік:',
    NET_MONTH_INCOME: 'Чистий дохід на місяць:',
    TAX_DESCRIPTION_PART_0: 'Переглянути деталі розрахунку',
    TAX_DESCRIPTION_PART_1: 'ФОП:',
    TAX_DESCRIPTION_PART_2: 'Податок на прибуток: ',
    TAX_DESCRIPTION_PART_3: '(ставка може корегуватись, в залежності від виду діяльності)',
    TAX_DESCRIPTION_PART_4_1: 'Калькулятор розраховує ваш чистий дохід, з урахуванням податків.',
    TAX_DESCRIPTION_PART_4_2: 'Розрахунок орієнтовний та не враховує ваше сімейне становище та кількість дітей, що може впливати на податкові ставки у різних країнах.',
    TITLE: 'Рекомендації щодо тимчасового переміщення IT фахівців',
    SUBTITLE: 'Оберіть країну:',
    COUNTRY_DETAILS_LINK_TEXT: 'Детальна інформація по країні',
    CALCULATOR_TITLE: 'Розрахуйте свій приблизний прибуток:',
}